qa_dict = {
   "hay": "𝐇𝐚𝐲 {username} 𝐌𝐞𝐫𝐚 𝐁𝐚𝐛𝐮 𝐍𝐞 𝐓𝐡𝐚𝐧𝐚 𝐓𝐡𝐚𝐲𝐚",
    "hello": "𝐇𝐞𝐥𝐥𝐨 {username} 𝐇𝐨𝐰 𝐚𝐫𝐞 𝐲𝐨𝐮?",
    "hii": "𝐡𝐢𝐢 {username} 𝑲𝒚𝒂 𝑯𝒂𝒍 𝑯𝒂𝒊 𝒔𝒖𝒃 𝒎𝒔𝒕 😎",
    "hi": "𝐡𝐢𝐢 {username} 𝑲𝒚𝒂 𝑯𝒂𝒍 𝑯𝒂𝒊 𝒔𝒖𝒃 𝒎𝒔𝒕 😎",
    "hiii": "𝐡𝐢𝐢 {username} 𝑲𝒚𝒂 𝑯𝒂𝒍 𝑯𝒂𝒊 𝒔𝒖𝒃 𝒎𝒔𝒕 😎",
    "kay hal hay": "𝐌𝐞𝐫𝐚 𝒎𝒔𝒕 😎 ",
    "help": "<b>Request Accept Send Me Your Broblem @Itachiuchhiihaa</b>",
    "hy": "𝐇𝐚𝐲 {username} 𝗞𝘆𝗮 𝗛𝗮𝗹 𝗛𝗮𝗶",
    "bro": "{username} 𝐁ⱺᥣⱺ 𝐕𝗋ⱺ 😎",
    "admin": "<b>Request Accept Send Me Your Problem @Itachiuchhiihaa</b>",
    "req": "<b>Request Accept Send Me Your Problem @Itachiuchhiihaa</b>", 
    "buy": "𝐆𝐨𝐨𝐝𝐛𝐲𝐞! {username} 𝐈 𝐌𝐢𝐬𝐬 𝐘𝐨𝐮 🥺",
    "good morning": "𝗴𝗼𝗼𝗱 𝗠𝗼𝗿𝗻𝗶𝗻𝗴 {username} 😁",
    "goodmorning": "𝗴𝗼𝗼𝗱 𝗠𝗼𝗿𝗻𝗶𝗻𝗴 {username} 😁",
     "gm": "𝗴𝗼𝗼𝗱 𝗠𝗼𝗿𝗻𝗶𝗻𝗴 {username} 😁",
    "good night": "𝐀 𝐓𝐨 𝐉𝐚 𝐑𝐞 {username}😴",
    "goodnight": "𝐆𝐨𝐨𝐝 𝐍𝐢𝐠𝐡𝐭 {username}😴 ",
    "gn": "𝐆𝐨𝐨𝐝 𝐍𝐢𝐠𝐡𝐭 {username}😴 𝐒𝐨 𝐉𝐚 𝐁𝐡𝐢 ",
    "ram ram": "𝐑𝐚𝐦 𝐑𝐚𝐦 𝐁𝐡𝐢 𝐉𝐞",
    "jay shree ram": "𝐉𝐚𝐲 𝐒𝐡𝐫𝐞𝐞 𝐑𝐚𝐦",
    "jay shree krishna": "𝐉𝐚𝐲 𝐒𝐡𝐫𝐞𝐞 𝐊𝐫𝐢𝐬𝐡𝐧𝐚 𝐁𝐡𝐢 𝐣𝐢❤️",
    "om namah shivaya": "𝐎𝐦 𝐍𝐚𝐦𝐚𝐡 𝐒𝐡𝐢𝐯𝐚𝐲𝐚 𝐁𝐡𝐢 𝐉𝐢❤️",
    "bye": "𝐆𝐨𝐨𝐝𝐛𝐲𝐞! {username} 𝐈 𝐌𝐢𝐬𝐬 𝐘𝐨𝐮 🥺",
    "see you later": "𝐌𝐞 𝐓𝐨",
    "okay": "𝐎𝐤𝐚𝐲! 😁",
    "ok": "𝐎𝐤𝐚𝐲! 😁",
    "cool": "𝐂𝐨𝐨𝐥! 𝐍𝐚𝐡𝐢 𝐁𝐡𝐢 𝐇𝐨𝐭 𝐁𝐨𝐥",
    "awesome": "𝐀𝐚𝐲𝐚",
    "great": "𝐇𝐚𝐚 𝐆𝐫𝐞𝐚𝐭 𝐓𝐨 𝐇𝐚𝐲",
    "nice": "𝐓𝐡𝐚𝐧𝐤",
}
